
##########################################
###### This file was autogenerated. ######
######### DO NOT EDIT this file. #########
##########################################
### file to edit: dev_nb/imflash217__01_matmul.ipynb ####

from exp.nb_00_exports import *
import operator

def test(a, b, cmp, cname=None):
    if cname is None:
        cname = cmp.__name__
    assert cmp(a, b), f"{cname}:\n{a}\n{b}"

def test_eq(a,b):
    test(a, b, operator.eq, "==")

### test whether the results from two methods are same or not
### as its difficult to accurately achieve the same numbers due to floating-point operation
### we will create a function to test whether two tensor (of same shape) are
### APPROXIMATELY EQUAL withing some tolerance

def near(a, b):
    return torch.allclose(input=a, other=b, rtol=1e-3, atol=1e-5)
def test_near(a, b):
    return test(a=a, b=b, cmp=near)