
##########################################
###### This file was autogenerated. ######
######### DO NOT EDIT this file. #########
##########################################
### file to edit: dev_nb/imflash217__04_lsuv.ipynb ####

from exp.nb_03_batchnorm import *

def get_batch(dl, run):
    run.xb, run.yb = next(iter(dl))
    for cb in run.cbs:
        cb.set_runner(run)
    run("begin_batch")
    return run.xb, run.yb

def find_modules(module, cond):
    if cond(module):
        return [module]
    return sum([find_modules(m, cond) for m in module.children()], [])

def is_lin_layer(l):
    lin_layers = (torch.nn.Conv1d, torch.nn.Conv2d, torch.nn.Conv3d, torch.nn.Linear, torch.nn.ReLU)
    return isinstance(l, lin_layers)

def lsuv_module(module, xb):
    h = Hook(module, append_stat)

    while learner.model(xb) is not None and abs(h.mean) > 1e-3:
        module.bias -= h.mean
    while learner.model(xb) is not None and abs(h.std-1) > 1e-3:
        module.weight.data /= h.std

    h.remove()
    return h.mean, h.std